language: node_js
sudo: false
addons:
  artifacts: true
node_js:
  - "8.11.0"
install:
  - npm install
script:
  - npm run build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AccessKeyID
  secret_access_key: $SecretAccessKey
  bucket: mattcale-blog
  skip_cleanup: true
  local_dir: dist
  cache_control: "max-age=21600"
